

CREATE DATABASE IF NOT EXISTS json_database;

CREATE TABLE IF NOT EXISTS json_database.s3_data(
id INT PRIMARY KEY,
name VARCHAR(256) NOT NULL,
value DECIMAL(4,1) NOT NULL,
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);


SHOW DATABASES;


