
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrong@Passw0rd"
      MYSQL_DATABASE: "json_database"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "YourStrong@Passw0rd"
    volumes:
      - "./mysql_DDL:/docker-entrypoint-initdb.d/:rwx"
    networks:
      - localstack_network 

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3,lambda,ec2,sqs # Enable the AWS services you need
      - DEBUG=1                    # Enable debugging
      - DATA_DIR=/tmp/localstack/data # Persist data between restarts
      - DEFAULT_REGION=us-east-1   # Set default AWS region
      - LAMBDA_EXECUTOR=docker-reuse # Use Docker for Lambda execution
    ports:
      - "4566:4566"                # LocalStack edge port for all services
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack_network

networks:
  localstack_network:
    driver: bridge
