
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd"
      MYSQL_DATABASE: "json_database"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "Passw0rd"
    volumes:
      - "./mysql_DDL:/docker-entrypoint-initdb.d/:rwx"
    dns:
      - 10.0.2.20
    networks:
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3,lambda,ec2,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker-reuse
    ports:
      - "4566:4566"
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      localstack:
        ipv4_address: 10.0.2.20

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    volumes:
      - "./:/workspace"
    working_dir: /workspace
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "terraform init &&
       terraform apply -auto-approve"
    depends_on:
      - localstack
      - mysql
    dns:
      - 10.0.2.20
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - localstack

networks:
  localstack:
    ipam:
      config:
        - subnet: 10.0.2.0/24
