
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd"
      MYSQL_DATABASE: "json_database"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "Passw0rd"
    volumes:
      - "./mysql_DDL:/docker-entrypoint-initdb.d/:rwx"
    networks:
      - localstack_network 

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3,lambda,ec2,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker-reuse
    ports:
      - "4566:4566"
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack_network

networks:
  localstack_network:
    driver: bridge
